name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_release:
    name: ビルド & リリース
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: リソースパックとして機能するディレクトリを見つける
        run: find . -mindepth 2 -maxdepth 2 -type f -iname pack.mcmeta | parallel echo {//} > pack.txt

      - name: 見つけたディレクトリからリソースパックの作成
        run: parallel -a pack.txt --wd {} zip -r "$PWD"/{/}.zip .

      - name: 作成したリソースパックを表示する
        run: find . -maxdepth 1 -type f -name "*.zip"

      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: action-v${{ github.run_number }}
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
